source 'https://rubygems.org'

gem 'mysql2'
gem 'rails', '5.0.7'
gem 'puma'
gem 'pg'
gem 'figaro'
gem 'redis'
gem 'listen'
gem 'slim'
gem 'sass-rails'
gem 'jquery-rails'
gem 'uglifier'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'simple_form', github: 'plataformatec/simple_form'
gem 'autoprefixer-rails'
gem 'mini_racer'

